{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Активные запросы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "myapp_active_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество запросов в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(myapp_request_count[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество ошибок",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(myapp_error_count[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Общее число запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "myapp_request_count{job=\"metricsapp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время выполнения запроса",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(myapp_request_duration_seconds_sum[1m]) / rate(myapp_request_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Размер запросов",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(myapp_request_size_bytes_sum[1m]) / rate(myapp_request_size_bytes_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}