<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!--fluent-validation-->
    <PackageVersion Include="FluentValidation" Version="11.9.0" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="7.0.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="7.0.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
    <!--mongo-->
    <PackageVersion Include="MongoDB.Bson" Version="2.29.0" />
    <PackageVersion Include="MongoDB.Driver" Version="2.23.1" />
    <!--redis-->
    <PackageVersion Include="StackExchange.Redis" Version="2.8.16" />
    <PackageVersion Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="7.0.17" />
    <!-- asp packages -->
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="7.0.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.7.2" />
  </ItemGroup>
</Project>