<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
      <ProjectReference Include="..\..\BoardApp.Core\BoardApp.Core.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <!-- Явно фиксируем корневой namespace: Razor-файлы генерируют классы
             вида PageController.Pages.IndexModel на его основе -->
        <RootNamespace>PageController</RootNamespace>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

</Project>
